---
title: "report"
output: html_document
date: "2023-10-25"
---

```{r, echo=FALSE, message=F, warning=FALSE}

# Load libraries
rm(list = ls())
library(httr)
library(stringr)
library(lmtest)
library(broom)
library(lubridate)
library(openxlsx)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(knitr)
library(reshape2)
library(kableExtra)

merged_data <- read.csv("source_data/merged_data.csv")

```

```{r}
#generate race count figure

merged_data <- read.csv("source_data/merged_data.csv")


#recode Race so that any response with multiple responses is "Multiple"
unique(merged_data$Race...Ethnicity)

merged_data$Race...Ethnicity[str_detect(merged_data$Race...Ethnicity, ",")] = "Multiple"

# Check the unique values in the modified variable
unique(merged_data$Race...Ethnicity)

category_counts <- table(merged_data$Race...Ethnicity)

# Create a data frame for plotting
category_data <- data.frame(Category = names(category_counts), Count = as.numeric(category_counts))

# Create a bar plot
ggplot(category_data, aes(x = Category, y = Count)) +
  geom_bar(stat = "identity") +
  labs(x = "Race...Ethnicity", y = "Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
  panel.background = element_rect(fill = "white"))

# Save the plot as a PNG file in the 'output' folder 
ggsave("output/racecount_figure.png", width = 6, height = 4)


```

```{r}
#generate racetime figure

# Convert the "DLC" column to a Date object
merged_data$DLC <- mdy(merged_data$DLC)  # Assumes month-day-year format, adjust if needed

# Calculate the difference between today and the "DLC" dates
merged_data$Days_In_Dataset <- as.numeric(difftime(Sys.Date(), merged_data$DLC, units = "days"))

# Create a summary data frame with the average length of time by "Race...Ethnicity"
summary_dataR <- aggregate(Days_In_Dataset ~ Race...Ethnicity, data = merged_data, FUN = mean)

# Create a bar plot
ggplot(summary_dataR, aes(x = Race...Ethnicity, y = Days_In_Dataset)) +
  geom_bar(stat = "identity") +
  labs(x = "Race...Ethnicity", y = "Average Length of Time") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.background = element_rect(fill = "white"))

# Save the plot as a PNG file in the 'output' folder 
ggsave("output/racetime_figure.png", width = 6, height = 4)

```

```{r}
#generate sex figure


summary_dataS <- aggregate(Days_In_Dataset ~Sex, data = merged_data, FUN = mean)

# Create a bar plot
ggplot(summary_dataS, aes(x = Sex, y = Days_In_Dataset)) +
  geom_bar(stat = "identity") +
  labs(x = "", y = "Average Length of Time") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 0, hjust = 1),
         panel.background = element_rect(fill = "white"))

# Save the plot as a PNG file in the 'output' folder 
ggsave("output/sex_figure.png", width = 6, height = 4)

```






```{r, echo=FALSE, message=F, warning=FALSE}

#generate state figure

ggplot(merged_data, aes(x = State)) +
  geom_bar(fill = "lightblue") +
  labs(title = "Missing Persons by State") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 80, hjust = 1),
               panel.background = element_rect(fill = "white"))

# Save the plot as a PNG file in the 'output' folder 
ggsave("output/state_figure.png", width = 6, height = 4)


```


```{r, echo=FALSE, message=F, warning=FALSE}
#generate age group figure

# Ensure that 'Missing.Age' is a character column
merged_data$Missing.Age <- as.character(merged_data$Missing.Age)

# Create age bins in groups of 5
merged_data$Age_Group <- cut(as.numeric(gsub(" Years", "", merged_data$Missing.Age)), 
                            breaks = seq(0, max(as.numeric(gsub(" Years", "", merged_data$Missing.Age)), na.rm = TRUE) + 5, by = 5),
                            labels = paste0(seq(0, max(as.numeric(gsub(" Years", "", merged_data$Missing.Age)), na.rm = TRUE), by = 5), "-", seq(4, max(as.numeric(gsub(" Years", "", merged_data$Missing.Age)), na.rm = TRUE) + 4, by = 5)))

# Create a data frame with the count of missing persons by age group
missing_by_age_group <- merged_data %>%
  group_by(Age_Group) %>%
  summarise(Count = n())

# Create a bar chart for missing persons by age group
ggplot(missing_by_age_group, aes(x = reorder(Age_Group, -Count), y = Count, fill = Age_Group)) +
  geom_bar(stat = "identity", width = 0.5) +
  labs(title = "Missing Persons by Age Group", x = "Age Group") +  # Set x-axis label
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.background = element_rect(fill = "white"))+
  guides(fill = "none")  
             

# Save the plot as a PNG file in the 'output' folder 
ggsave("output/age_group_figure.png", width = 6, height = 4)

```


```{r}
# linear regression: sex

library(lmtest)
library(tidyverse)

# Create a linear regression model
model_sex <- lm(Days_In_Dataset ~ Sex, data = merged_data)

# Check the model summary
sum_model_sex <- summary(model_sex)

# Tidy the model results
tidy_model_sex <- tidy(model_sex)

# Display the tidy model results in a table
print(tidy_model_sex)

```

```{r}
#linear regression: race/ethnicity

library(lmtest)
library(tidyverse)

# Convert 'Race...Ethnicity' to a factor
merged_data$Race...Ethnicity <- as.factor(merged_data$Race...Ethnicity)

# Set "White / Caucasian" as the reference category
merged_data$Race...Ethnicity <- relevel(merged_data$Race...Ethnicity, ref = "White / Caucasian")

model_race <- lm(Days_In_Dataset ~ Race...Ethnicity, data = merged_data)

#model summary
sum_model_race <- summary(model_race)

tidy_model_race <- tidy(model_race)

# Display the tidy model results in a table
print(tidy_model_race)
```

